### ISSUE TITLE
Many missing methods from the official selenium API are not implemented

### ISSUE THREAD

**Issue by totty90** [jsdevel/webdriver-sync#100]
You can see the api here: http://selenium.googlecode.com/git/docs/api/javascript/class_webdriver_WebDriver.html

Missing methods:

 - isElementPresent
 - getAllWindowHandles

**Comment by jsdevel** [comment]
`element.isDisplayed()` should handle `isElementPresent`  See https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/WebElement.html

'driver.getWindowHandles()` should handle `getAllWindowHandles`  See https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/WebDriver.html#getWindowHandles()

**Comment by totty90** [comment]
Thanks, I've figured out later. Wouldn't be better to have an unified API for selenium?

**Comment by totty90** [comment]
>element.isDisplayed() should handle isElementPresent

I've done this:

    expect(this.driver.findElements(this.By.cssSelector('#css')).length).to.be.equal(1);

**Comment by jsdevel** [comment]
> Wouldn't be better to have an unified API for selenium?
It really would.  Not sure why it differs between the bindings.

> I've done this
I think it should be:
`expect(this.driver.findElements(this.By.cssSelector('#css')).length).to.equal(1);`

**Comment by totty90** [comment]
>It really would. Not sure why it differs between the bindings.

Anyway is very messy. 

I still have my doubts that I understand how it works but here it is:

 - When creating a new driver is like creating a new user profile in chrome;
 - When opening a window, is opening a window in the same profile in chrome; (shares the same sessions)

Therefore you can have multiple profiles and windows at the same time, I'm right? I'm thinking in wrapping all this in some more understandable way.

>I think it should be:

I think both works (mine works for sure, because has been tested). I use chai.

**Comment by jsdevel** [comment]
> Therefore you can have multiple profiles and windows at the same time, I'm right? I'm thinking in wrapping all this in some more understandable way.

Yes I believe that is correct.  `new ChromeDriver()` is like clicking the application shortcut to open a fresh chrome window.

> I think both works (mine works for sure, because has been tested). I use chai.

Interesting.  I didn't know chai supported `.to.be.equal`.  Doesn't sound grammatically correct.

**Comment by totty90** [comment]
Hy!

As I've said I've wrapped the selenium API into my own and looks pretty good, is sync and not blocking. Here is an example, what do you think?

    var rootW = browser.getCurrentWindow();
    rootW.goTo('https://localhost:5003');
    console.log('window title', rootW.getTitle())
    browser.waitToHaveAtLeastXWindows(2);
    var facebookW = browser.getWindowByIndex(1);
    browser.switchToWindow(facebookW);
    facebookW.waitToLoad();
    facebookW.waitForElement('#email');
    // Let facebook to setup its ui.
    browser.sleep(500);
    var el = facebookW.findEl('#email');
    el.click();
    el.sendKeys('test');

**Comment by jsdevel** [comment]
looks pretty good to me!

**Comment by totty90** [comment]
Thanks, I will open source tomorrow (:
