### ISSUE TITLE
LocalFileDetector does not seem to work

### ISSUE THREAD

**Issue by alanfreer** [jsdevel/webdriver-sync#105]
We are trying to use webdriver-sync (0.15.8) to write a test of a file upload feature.  This works fine when running locally but now we are trying to get the test to run against sauce labs

I saw this article on the sauce labs website:
https://saucelabs.com/resources/selenium-file-upload

I was hoping to use driver.setFileDetector(localFileDetector) so that files are uploaded automatically to the remote selenium server on sauce labs and then sendKeys(localPathToFileIWantToUpload) to set the local path.  I expect that on the remote selenium server some magic happens where the uploaded file is made available during the post request to the website being tested.

I can see that webdriver-sync has a wrapper class LocalFileDetector.js.  However, I cannot figure out how to get an instance of LocalFileDetector so I can call driver.setFileDetector.  The best I've managed is to get the line of code below to run.  However, it returns a plan javascript object which isn't an instance of FileDetector.  I get an exception in setFileDetector because of that.

var webdriver = require('webdriver-sync');
var detector = webdriver.LocalFileDetector;
driver.setFileDetector(detector); // driver is an instance of webdriver.RemoteWebDriver(...)

Is this supported?  If it is could you send me an example of how to get hold of an instance of LocalFileDetector please?

I appreciate any thoughts on whether this is implemented and how it works.  Apologies in advance if I have misunderstood how to use the API.

**Comment by jsdevel** [comment]
Looks like [LocalFileDetector](https://github.com/jsdevel/webdriver-sync/blob/master/src/classes/LocalFileDetector.js) isn't exported via `module.exports`.

You can likely fix it by adding `module.exports = LocalFileDetector;` to line 9.

**Comment by jsdevel** [comment]
[Here](https://github.com/jsdevel/webdriver-sync/blob/master/src/webdriver-sync.js) is the main file that is exposed by `require('webdriver-sync');`.  As you can see, there is an export for `LocalFileDetector`.

**Comment by jsdevel** [comment]
Just published `v0.15.9`.  Let me know how it works @alanfreer.  Thanks for reporting this!

**Comment by alanfreer** [comment]
I just tried 0.15.9 and everything is working now.  Thanks for fixing this so quickly - I really appreciate it!

**Comment by jsdevel** [comment]
Thanks for reporting!
