### ISSUE TITLE
Chromedriver 2.15 required for performance logs on Chrome 42

### ISSUE THREAD

**Issue by NickTulett** [jsdevel/webdriver-sync#106]
Otherwise you get an error on starting the browser when you have "performance" enabled in Chrome's loggingPreferences:

org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Timeline is deprecated. Please use Tracing instead"}
  (Session info: chrome=42.0.2311.90)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-49-generic x86_64) (WARNING: The server did not provide any stacktrace information)

**Comment by jsdevel** [comment]
Next `npm install` should pick it up.  Updated in `selenium-binaries`.  Thanks for reporting @NickTulett !
