### ISSUE TITLE
setSessionId on RemoteWebDriver

### ISSUE THREAD

**Issue by dirwin517** [jsdevel/webdriver-sync#111]
any chance is there a way to give it a sessionId, looks like remoteWebDriver should have a setSessionId?
(we wanted to run protractor tests, but switch to webdriver-sync for any non angular intense operations)

**Comment by jsdevel** [comment]
There is a method on `RemoteWebDriver`  setSessionId.  It just takes a string.  `getSessionId` returns this: https://github.com/jsdevel/webdriver-sync/blob/master/src/classes/SessionId.js.

**Comment by jsdevel** [comment]
Why wouldn't you use it for angular applications as well?

**Comment by dirwin517** [comment]
1. protractor gives a lot of functionality ontop of webdriver, that is specific to angular apps, we would have to implement a bunch of xpath locators for angular by.ngmodel/by.repeater/by.cssContainingText, etc attributes and scripts for waitForAngular() / evaluate() and so on, to introspect and wait for angular to digests

2. we have legacy cucumber tests which use protractor, but want newer tests to be able to use old functions, but also write new steps with webdriver-sync, that we need on occasion

so we'd want to use webdriver-sync in conjunction with protractor, requiring us to have them share a session together

**Comment by jsdevel** [comment]
We could get their selectors in webdriver-sync as an add on.

**Comment by NickTulett** [comment]
I'm also testing an Angular app (without protractor) and as a rule I tend to avoid xpath selectors. I ran some benchmarks and they were 5-10 times slower than the straight css alternatives.

e.g.
```javascript
input[ng-model='newLayout.file']
li[ng-click="model.routeParams.selectedTab = 'devices'"]
button[ng-click='deleteITActuals()']
a[ng-click='openModelDialog(variation)']
tr[ng-repeat='file in uploadedFiles']
```
etc.

**Comment by jsdevel** [comment]
@NickTulett I'd love to see some best practices you've encountered on selenium testing angular without protractor.  I've been automating a lot lately with Java 8 and page objects.  Polling pending requests and using `$timeout` have proven to be invaluable, but wanted to know if you had any other things to say about it.

Also, checkout this blog article on page objects and re-usable components as mixins:  http://blog.jsdevel.me/2015/04/pageobjects-done-right-in-java-8.html.  That one is for java, but there's also one for node that would work well with `webdriver-sync`.

**Comment by NickTulett** [comment]
Maybe we're doing Angular wrong but I'm not doing anything I wouldn't do on any other web project, ng just provides/requires an extra set of alternative css selectors. At the system test level I don't care that it's Angular that's creating the page, just what the end result is.
