### ISSUE TITLE
Just upgraded to Yosemite . . . and now it's broken?

### ISSUE THREAD

**Issue by tandrewnichols** [jsdevel/webdriver-sync#115]
Not sure if this a webdriver-sync issue, or a node-java issue, or a find-java-home issue. Starting here because I've been here before. Just upgraded my mac to Yosemite and started getting errors about needing to move to a legacy version of Java (1.6). Found a post that suggests that Yosemite does not support java 7, only java 8 jre and some older versions. I was able to get past the warnings and get a working version of jdk 7 (meaning . . . it actually _tried_ to execute the webdriver specs, rather than just throwing the upgrade warning). But now I get the following:

![screen shot 2015-06-26 at 4 02 27 pm](https://cloud.githubusercontent.com/assets/2755760/8386384/eebac156-1c1d-11e5-93f5-f15bba79f956.png)

If I remember correctly, webdriver-sync (or one of the underlying pieces, node-java I think) requires a jdk version, not a jre. But it appears that both java 7 jdk and java 8 jdk won't work on Yosemite. Have you heard this from anyone else? Know how they resolved it? Have suggestions?

(N.B. It is possible I have things set up wrong. Java never makes things easy.)

**Comment by NickTulett** [comment]
I have it working on a Yosemite vm. May not be able to get access to it before Monday to confirm how I set it up but don't remember any issues.

**Comment by tandrewnichols** [comment]
So I had to

```
rm -rf ~/.selenium-binaries node_modules/selenium-binaries node_modules/webdriver-sync
npm i webdriver-sync selenium-binaries
```

and now it works. Somehow, the selenium jar wasn't part of the classpath . . . or . . . something. At any rate, starting over worked out.

**Comment by jsdevel** [comment]
thanks @tandrewnichols !
