### ISSUE TITLE
Keys.ARROW_DOWN behaves strangely

### ISSUE THREAD

**Issue by tandrewnichols** [jsdevel/webdriver-sync#118]
I'm trying to use Keys.ARROW_DOWN to select an element from a dropdown after typing text in an input. This _does_ arrow down . . . but it does it in perpetuity. I.e. it's like I'm holding the key down . . . forever. It just cycles through the dropdown list items over and over.

It's possible this is an issue with other keys as well, but I haven't tested.

Here's the entirety of the code:

```coffee
describe.only 'listing manager ppc landing page', ->
  Given -> browser.visit '/listingmanager'
  When (done) -> browser.wait ( -> $('form[name="dittoForm"]').visible() ), done
  Then -> $('[name="name"]').sendKeys 'Banana'
  And -> $('[name="name"]').sendKeys browser.wd.Keys.ARROW_DOWN
```

Sorry for the coffeescript . . .

**Comment by tandrewnichols** [comment]
Oh! Disregard . . . I know why this is happening. It's something in our own wrapper of this library. Sorry for the false alarm!

**Comment by jsdevel** [comment]
no worries.  Glad you were able to resolve it!
