### ISSUE TITLE
Update to java@0.5.4

### ISSUE THREAD

**Issue by Artazor** [jsdevel/webdriver-sync#120]
Will it break something?

Btw, it would be great to update selenium binaries as well: https://github.com/spunjs/selenium-binaries/pull/6

**Comment by Artazor** [comment]
@jsdevel 
Hmm... Looks like Build on travis has failed for Node 0.12. However it shows that all things are built ok, tests passed but suddenly something has hanged. Can you investigate it? When I've created this pull request Travis CI indicated that all is ok.

**Comment by jsdevel** [comment]
Sometimes it needs to be re-run.  Not sure why.  It's running now so we'll see.
