### ISSUE TITLE
Possible tu use with Electron?

### ISSUE THREAD

**Issue by LeMoussel** [jsdevel/webdriver-sync#124]
Possible to use webdriver-sync with [Electron](https://github.com/atom/electron) & chromedriver binary?

Usage of selenium-webdriver with Electron is basically the same with upstream, except that you have to manually specify how to connect chrome driver and where to find Electron's binary:
[selenium-webdriver](http://seleniumhq.github.io/selenium/docs/api/javascript/) provided a Node package for Electron with web driver.

**An example**

```javascript
var webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder()
  // The "9515" is the port opened by chrome driver.
  .usingServer('http://localhost:9515')
  .withCapabilities({chromeOptions: {
    // Here is the path to your Electron binary.
    binary: '/Path-to-Your-App.app/Contents/MacOS/Atom'}})
  .forBrowser('electron')
  .build();

driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(function() {
 return driver.getTitle().then(function(title) {
   return title === 'webdriver - Google Search';
 });
}, 1000);

driver.quit();
```

**Comment by jsdevel** [comment]
I'm not very familiar with Electron.  Is that like an editor?

**Comment by LeMoussel** [comment]
No. Electron is a framework that lets you write cross-platform desktop applications using JavaScript, HTML and CSS. It is based on io.js and Chromium. Electron uses web pages as its GUI, so you could also see it as a minimal Chromium browser, controlled by JavaScript.

**Comment by jsdevel** [comment]
If you can view the project in a browser, then you should be able to test it with `webdriver-sync`.
