### ISSUE TITLE
Cant pass a WebElement as an argument to script via executeScript

### ISSUE THREAD

**Issue by SkReD** [jsdevel/webdriver-sync#89]
Try to do this:

driver.executeScript('return arguments[0]', this.elems[0])

where this.elems is an array of WebElement's. Result of executeScript is null.

**Comment by jsdevel** [comment]
What would be the intended result?

**Comment by jsdevel** [comment]
I do see an issue now with the [code](https://github.com/jsdevel/webdriver-sync/blob/master/src/interfaces/JavascriptExecutor.js#L56).  It should `.map()` all the `args` to their native java equivalents for `node-java` to access them appropriately.

@SkReD do you think you can update this?  It may have to wait till tonight before I can.

**Comment by SkReD** [comment]
Better do it by yourself, i can try only tomorrow

**Comment by jsdevel** [comment]
@SkReD published `v0.15.2` to allow this.  Let me know how it works.  Thanks!
