### ISSUE TITLE
Error: Cannot find module './binary-paths.json'

### ISSUE THREAD

**Issue by totty90** [jsdevel/webdriver-sync#91]
Just installed on a clean windows 7 and run this file:

    var wd = require('webdriver-sync');
    var ChromeDriverService = wd.ChromeDriverService;
    var ChromeDriver = wd.ChromeDriver;
    var service = new ChromeDriverService.Builder()
        .usingAnyFreePort()
        .usingDriverExecutable(new File(findsChromeDriver.find()))
        .build();

    var driver = new ChromeDriver(service);
    driver.get('http://google.com');

And got this error:

    module.js:340
        throw err;
              ^
    Error: Cannot find module './binary-paths.json'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (C:\app\node_modules\webdriver-sync\node_modules\selenium-binaries\index.js:4:18)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)

What is wrong? The chromedriver is added to the PATH, but I think is not needed in this lib.

    C:\Users\s>java -version
    java version "1.7.0_45"
    Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
    Java HotSpot(TM) Client VM (build 24.45-b08, mixed mode, sharing)

Already installed twice.

>Ensure that your environment is setup to compile node add ons. A good module to use in verifying that you can compile node addons is microtime.

I don't understand what microtime has to do with making node to compile node add ons.

**Comment by jsdevel** [comment]
Hmm.  `selenium-binaries` creates `binary-paths.json` in it's install directory.  Can you verify that it does not exist by looking in `webdriver-sync/node_modules/selenium-binaries/binary-paths.json`?

**Comment by totty90** [comment]
There is no webdriver-sync/node_modules/selenium-binaries/binary-paths.json file...

**Comment by jsdevel** [comment]
hmm.  That's strange.  Can you install `selenium-binaries` to troubleshoot?  It works on my machine (linux).

**Comment by guyhill** [comment]
I got the same error on a 32-bit Windows 7 machine. I think it is related to the most recent version (0.15.3) of webdriver-sync: installing version 0.15.2 solved the problem for me.

**Comment by jsdevel** [comment]
@guyhill what's wierd is `windows8@64bit` installed just fine.

**Comment by jsdevel** [comment]
@totty90 @guyhill based on [the selenium binaries code](https://github.com/spunjs/selenium-binaries/blob/master/lib/install.js#L163), it looks like if an error occurs while downloading the binary dependencies then `binary-paths.json` will not get created.  Can you guys try re-installing and paste the full `npm install` output?  I'm thinking there was some error occurred that prevented the file from being created.

**Comment by jsdevel** [comment]
Tried on `windowsVista@32bit` with no issues either.

**Comment by jsdevel** [comment]
@totty90 @guyhill can you try `0.15.4`?

**Comment by totty90** [comment]
C:\web\a>npm install selenium-binaries
    npm WARN package.json a@1.0.0 No repository field.
    npm WARN package.json a@1.0.0 No README data
    -
    > selenium-binaries@0.3.3 install C:\web\node_modules\selenium-binaries
    > node ./lib/install.js


    [selenium-binaries] Found Selenium at C:\Users\a\.selenium-binaries\selenium\2.44.0\selenium-server-standalone-2.44.0.jar

    [selenium-binaries] Found chromedriver at C:\Users\a\.selenium-binaries\chromedriver\2.14\chromedriver.exe

    [selenium-binaries] Found iedriver at C:\Users\a\.selenium-binaries\iedriver\2.44.0\IEDriverServer.exe
    selenium-binaries@0.3.3 ..\node_modules\selenium-binaries
    ├── which@1.0.8
    ├── is-dir@1.0.0
    ├── async@0.9.0
    ├── mkdirp@0.5.0 (minimist@0.0.8)
    ├── unzip@0.1.11 (setimmediate@1.0.2, pullstream@0.4.1, match-stream@0.0.2, readable-stream@1.0.33, fstream@0.1.31, binary@0.3.0)
    └── download@0.1.19 (get-stdin@0.1.0, each-async@0.1.3, get-urls@0.1.2, mkdirp@0.3.5, nopt@2.2.1, through2@0.4.2, decompress@0.2.5, request@2.53.0)

No binary-paths.json file created.

**Comment by totty90** [comment]
npm install selenium-binaries@0.3.2 same thing.

**Comment by totty90** [comment]
Log of npm install webdriver-sync@0.15.4

    C:\a>npm install webdriver-sync@0.15.4
    npm WARN package.json totty-project@1.0.0 No repository field.
    npm WARN package.json totty-project@1.0.0 No README data
    /
    > java@0.4.5 install C:\web\node_modules\webdriver-sync\node_modules\java
    > node-gyp rebuild


    C:\web\node_modules\webdriver-sync\node_modules\java>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
    es\node-gyp\bin\node-gyp.js" rebuild
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      java.cpp
      javaObject.cpp
      javaScope.cpp
      methodCallBaton.cpp
      nodeJavaBridge.cpp
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enab
    led. Specify /EHsc [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enab
    led. Specify /EHsc [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enab
    led. Specify /EHsc [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enab
    led. Specify /EHsc [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    C:\Users\a\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>
    ::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::Object
              ]
      utils.cpp
    C:\Users\a\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>
    ::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::Object
              ]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\utility(142): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
    istent<T>::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::Object
              ]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\utility(142): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
    istent<T>::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::FunctionTemplate
              ]
    C:\web\node_modules\webdriver-sync\node_modules\java\node_modules\nan\nan.h(1081): warning C4800: 'jboolean' : forcing value to bool
    'true' or 'false' (performance warning) [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              ..\src\java.cpp(1076) : see reference to function template instantiation 'v8::Local<T> NanNew<v8::Boolean,jboolean>(P)' being compiled
              with
              [
                  T=v8::Boolean,
                  P=jboolean
              ]
    C:\Users\a\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>
    ::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::Object
              ]
    C:\Users\a\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>
    ::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::FunctionTemplate
              ]
    c:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enab
    led. Specify /EHsc [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    ..\src\utils.cpp(525): warning C4800: 'jboolean' : forcing value to bool 'true' or 'false' (performance warning) [C:\web\node_modules
    \webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    C:\web\node_modules\webdriver-sync\node_modules\java\node_modules\nan\nan.h(1081): warning C4800: 'jboolean' : forcing value to bool
    'true' or 'false' (performance warning) [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              ..\src\utils.cpp(440) : see reference to function template instantiation 'v8::Local<T> NanNew<v8::Boolean,jboolean>(P)' being compiled
              with
              [
                  T=v8::Boolean,
                  P=jboolean
              ]
    C:\Users\a\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>
    ::New(v8::Handle<T>)' [C:\web\node_modules\webdriver-sync\node_modules\java\build\nodejavabridge_bindings.vcxproj]
              with
              [
                  T=v8::Object
              ]
         Creating library C:\web\node_modules\webdriver-sync\node_modules\java\build\Release\nodejavabridge_bindings.lib and object C:\web\node_modules\webdriver-sync\node_modules\java\build\Release\nodejavabridge_bindings.exp
      Generating code
      Finished generating code
      nodejavabridge_bindings.vcxproj -> C:\web\node_modules\webdriver-sync\node_modules\java\build\Release\\nodejavabridge_bindings.node

    > selenium-binaries@0.3.3 install C:\web\node_modules\webdriver-sync\node_modules\selenium-binaries
    > node ./lib/install.js


    [selenium-binaries] Found Selenium at C:\Users\a\.selenium-binaries\selenium\2.44.0\selenium-server-standalone-2.44.0.jar

    [selenium-binaries] Found chromedriver at C:\Users\a\.selenium-binaries\chromedriver\2.14\chromedriver.exe

    [selenium-binaries] Found iedriver at C:\Users\a\.selenium-binaries\iedriver\2.44.0\IEDriverServer.exe

    > java@0.4.5 postinstall C:\web\node_modules\webdriver-sync\node_modules\java
    > node postInstall.js

    webdriver-sync@0.15.4 ..\node_modules\webdriver-sync
    ├── async@0.2.10
    ├── selenium-binaries@0.3.3 (is-dir@1.0.0, which@1.0.8, async@0.9.0, mkdirp@0.5.0, unzip@0.1.11, download@0.1.19)
    └── java@0.4.5 (find-java-home@0.1.1, nan@1.4.1, glob@3.2.11)

**Comment by jsdevel** [comment]
Hmm.  Something really strange is happening.  It appears to have installed just fine.

**Comment by totty90** [comment]
Check the pull request from https://github.com/spunjs/selenium-binaries/issues/2 there is an error in the code.

**Comment by jsdevel** [comment]
thanks @totty90!  I just published `0.15.7` so you should be good to go.

**Comment by totty90** [comment]
Thanks
