### ISSUE TITLE
undefined is not a function, FindsByCssSelector

### ISSUE THREAD

**Issue by monster2015** [jsdevel/webdriver-sync#92]
Hi,

When calling the findElementsByCssSelector I get a 'TypeError: undefined is not a function'.

Looking into it, it looks like the findElements* calls are trying to call 'collectionsToArrayList' from utils.js, which doesn't exist.

Perhaps meant to be 'collectionToArray' in utils.js?

**Comment by jsdevel** [comment]
@monster2015 thanks for submitting this!  Can you provide a code-snippet that reproduces the error?

It would further be really cool if you could create a PR with a failing test case that reproduces this issue.

**Comment by monster2015** [comment]
The following code reproduces the error in node:

var wd = require('webdriver-sync');
var Chromedriver = wd.ChromeDriver;
var Browser = new ChromeDrive();

Browser.get('http://google.com');
Browser.findElementsByCssSelector('\mngb');

I'll have to think (how to do) about a test case.

**Comment by NickTulett** [comment]
```
var Chromedriver = wd.ChromeDriver;
var Browser = new ChromeDrive();
```
isn't that just a typo?
```
var Chromedriver = wd.ChromeDriver;
var Browser = new Chromedriver();
```

**Comment by monster2015** [comment]
Yes, my bad.

**Comment by jsdevel** [comment]
`var By = wd.By;  Browser.findElements(By.cssSelector('selector'));`

**Comment by monster2015** [comment]
Cool, that works for me. Is that the 'correct' way of doing things then?

Issue with user rather than code :-)

**Comment by jsdevel** [comment]
Yea, `webdriver-sync` is pretty much just a wrapper around the java api.  That's how java does it :tongue:
