### ISSUE TITLE
Tutorial doesn't work: ReferenceError: File is not defined (also findsChromeDriver)

### ISSUE THREAD

**Issue by totty90** [jsdevel/webdriver-sync#95]
The tutorial from the main page doesn't work:

    var wd = require('webdriver-sync');
    var ChromeDriverService = wd.ChromeDriverService;
    var ChromeDriver = wd.ChromeDriver;
    var service = new ChromeDriverService.Builder()
        .usingAnyFreePort()
        .usingDriverExecutable(new File(findsChromeDriver.find()))
        .build();

    var driver = new ChromeDriver(service);
    driver.get('http://google.com');

`File` and `findsChromeDriver` are not found.

**Comment by tandrewnichols** [comment]
`File` is on `wd`. Not sure where to get `findsChromeDriver` though.

**Comment by tandrewnichols** [comment]
Looks to me like findsChromeDriver doesn't exist anymore. Even searching the repo, I don't find anything except the readme reference. Even webdriver-sync itself doesn't use that in it's tests:

```js
if(process.env.TRAVIS){
  console.log('Hello Travis!');
  service = new ChromeDriverService.Builder()
    .usingAnyFreePort()
    .usingDriverExecutable(new File(seleniumBinaries.chromedriver))
    //.withEnvironment({'DISPLAY':':99.0'})
    //.withSilent(true)
    //.withVerbose(true)
    .build();
} else {
  service = ChromeDriverService.createDefaultService();
}
```

Where `seleniumBinaries` is from `require('selenium-binaries')` which is referenced on the readme as a useful 3rd party module. Looks to me like that function was removed and the docs weren't updated. @jsdevel, is that what happened?

**Comment by jsdevel** [comment]
@tandrewnichols most likely yes.
