### ISSUE TITLE
driver.manage().window().maximize() doesn't work

### ISSUE THREAD

**Issue by totty90** [jsdevel/webdriver-sync#97]

**Comment by totty90** [comment]
Now works :/ I've been wrapped the function with fibers.

**Comment by jsdevel** [comment]
Why fibers?

**Comment by totty90** [comment]
I've used fibers for the previous lib. I'm migrating from webdriver from selenium

**Comment by jsdevel** [comment]
Do you mean selenium-wedriver?  You shouldn't need fibers with webdriver-sync at all.

**Comment by totty90** [comment]
>Do you mean selenium-wedriver?

yes

> You shouldn't need fibers with webdriver-sync at all.

I know, but the test framework was using fibers by default and didn't remember to remove them before using the sync.

**Comment by jsdevel** [comment]
Gotcha!  Nice.  What's making you switch to `webdriver-sync`?  Got tired of promises?

**Comment by totty90** [comment]
>What's making you switch to webdriver-sync? Got tired of promises?

Of course, I never liked them. By the way your lib uses native node.js sync code, right? Isn't that blocking?

Related: 
My server side code +2500 lines with async is moving to the fiber based approach. I can't think I even started with async. Is very noisy compared with fibers. 100 lines of async converted to 10 lines of fibers.

**Comment by jsdevel** [comment]
> By the way your lib uses native node.js sync code, right? Isn't that blocking?

Correct.  It is blocking.  See the caveats section.

> My server side code +2500 lines with async is moving to the fiber based approach. I can't think I even started with async. Is very noisy compared with fibers. 100 lines of async converted to 10 lines of fibers.

For some things `sync` makes much more sense to me than `async`.  Browser testing is one case where that is so.  For other things like webservers, `async` is awesome.

**Comment by totty90** [comment]
>For some things sync makes much more sense to me than async. Browser testing is one case where that is so. For other things like webservers, async is awesome.

Fibers is not blocking but the syntax is sync. I have the best of both worlds. That's why I've asked you about considering to use fibers.

**Comment by jsdevel** [comment]
https://github.com/joeferner/node-java/issues/38

**Comment by totty90** [comment]
have you opened an issue on fibers too?

**Comment by jsdevel** [comment]
I haven't.
